package KieRule;
import com.zaloni.drooldemo.Order;

rule "Garbage collect rule"
salience -100
when
	$orderObject: Order();
then
    System.out.println($orderObject);
	delete($orderObject);
end;

rule "HDFC"
when
    $orderObject: Order(cardType=="HDFC" && price>10000);
then
    $orderObject.setDiscount(10);
end

rule "ICICI"
when
    $orderObject: Order(cardType=="ICICI" && price>15000);
then
    $orderObject.setDiscount(15);
end

